import teslaChargerImage from '../assets/charginStationTesla.jpeg';
import mahindraChargerStation from '../assets/chargingStationMahindra.jpeg';
import tataChargerImage from '../assets/chargingStationTata.jpeg';
import morrisChargerImage from '../assets/chargingStationMorris.jpeg';

export const availableCities = [
  { id: 'pune', name: 'Pune, Maharashtra', shortName: 'Pune', latitude: 18.5204, longitude: 73.8567, isDefault: true },
  { id: 'mumbai', name: 'Mumbai, Maharashtra', shortName: 'Mumbai', latitude: 19.0760, longitude: 72.8777 },
  { id: 'delhi', name: 'Delhi NCR & Gurugram', shortName: 'Delhi NCR', latitude: 28.4980, longitude: 77.0850 },
  { id: 'bengaluru', name: 'Bengaluru, Karnataka', shortName: 'Bengaluru', latitude: 12.9716, longitude: 77.5946 },
  { id: 'hyderabad', name: 'Hyderabad, Telangana', shortName: 'Hyderabad', latitude: 17.3850, longitude: 78.4867 },
];

export const currentUser = {
  name: 'Alex Rivera',
  email: 'alex.rivera@evdriver.com',
  vehicle: {
    model: 'Tata Nexon EV Max',
    brand: 'Tata',
    batteryCapacityKwh: 40.5,
    currentBatteryPct: 78,
    estimatedRangeKm: 284,
    maxRangeKm: 437,
    portType: 'CCS-2',
    fastChargeSpeedKw: 50,
  },
  defaultLocation: {
    latitude: 18.5204,
    longitude: 73.8567,
    address: 'FC Road, Shivajinagar, Pune, Maharashtra - 411005',
    city: 'Pune, Maharashtra',
  },
  walletBalance: 1450,
  currency: '₹',
  totalKwhCharged: 218.4,
  co2SavedKg: 136.8,
  savedStations: ['PUNE_TESLA_HINJAWADI', 'PUNE_TATA_BANER'],
};

export const manufacturerBrands = [
  { id: 'all', name: 'All Stations', icon: 'flash', color: '#05B66B' },
  { id: 'Tesla', name: 'Tesla', icon: 'car-sport', color: '#E82127' },
  { id: 'Tata', name: 'Tata Power', icon: 'battery-charging', color: '#0072CE' },
  { id: 'Mahindra', name: 'Mahindra', icon: 'shield-checkmark', color: '#C8102E' },
  { id: 'MG', name: 'Morris Garages', icon: 'speedometer', color: '#00539B' },
];

export const stations = [
  // ==========================================
  // PUNE EV CHARGING HUBS (Comprehensive Network)
  // ==========================================
  {
    id: 'PUNE_TESLA_HINJAWADI',
    city: 'pune',
    cityName: 'Pune, Maharashtra',
    company: 'Tesla',
    brandColor: '#E82127',
    stationName: 'Tesla Supercharger Hub - Hinjawadi Phase 1',
    address: 'Rajiv Gandhi Infotech Park, Hinjawadi Phase 1, Pune, Maharashtra - 411057',
    shortAddress: 'Hinjawadi Phase 1, Pune',
    latitude: 18.5913,
    longitude: 73.7389,
    distanceKm: 2.1,
    time: '6-8 Mins',
    timeMinutes: 7,
    image: teslaChargerImage,
    rating: 4.9,
    reviewsCount: 420,
    openHours: 'Open 24/7',
    totalPorts: 8,
    availablePortsCount: 6,
    maxPowerKw: 250,
    pricePerKwh: 22,
    connectorTypes: ['Tesla Supercharger', 'CCS-2', 'Type-2 AC'],
    amenities: ['24/7 IT Park Lounge', 'Coffee House', 'Restrooms', 'High-Speed Wi-Fi', 'Security'],
    ports: [
      { id: 'P1', name: 'Port 01 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 22 },
      { id: 'P2', name: 'Port 02 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 22 },
      { id: 'P3', name: 'Port 03 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'charging', pricePerKwh: 22 },
      { id: 'P4', name: 'Port 04 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 22 },
      { id: 'P5', name: 'Port 05 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 20 },
      { id: 'P6', name: 'Port 06 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 20 },
      { id: 'P7', name: 'Port 07 (AC Type 2)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 15 },
      { id: 'P8', name: 'Port 08 (AC Type 2)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 15 },
    ],
    description: 'Flagship Tesla V3 Supercharger station located at Hinjawadi Infotech Hub. Provides 250kW ultra-fast charging, executive waiting lounge, and dining options.',
  },
  {
    id: 'PUNE_TATA_BANER',
    city: 'pune',
    cityName: 'Pune, Maharashtra',
    company: 'Tata',
    brandColor: '#0072CE',
    stationName: 'Tata Power EZ Charge MegaHub - Baner',
    address: 'Balewadi High Street, Baner, Pune, Maharashtra - 411045',
    shortAddress: 'Balewadi High Street, Baner, Pune',
    latitude: 18.5590,
    longitude: 73.7794,
    distanceKm: 1.8,
    time: '5-7 Mins',
    timeMinutes: 5,
    image: tataChargerImage,
    rating: 4.8,
    reviewsCount: 680,
    openHours: 'Open 24/7',
    totalPorts: 8,
    availablePortsCount: 5,
    maxPowerKw: 120,
    pricePerKwh: 18,
    connectorTypes: ['CCS-2', 'Bharat DC-001', 'Type-2 AC'],
    amenities: ['Fine Dining', 'Café & Bakery', 'Clean Washrooms', 'Free Wi-Fi', 'EV Lounge'],
    ports: [
      { id: 'P1', name: 'Port 01 (Dual Gun DC)', type: 'CCS-2', powerKw: 120, status: 'available', pricePerKwh: 18 },
      { id: 'P2', name: 'Port 02 (Dual Gun DC)', type: 'CCS-2', powerKw: 120, status: 'available', pricePerKwh: 18 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P4', name: 'Port 04 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'charging', pricePerKwh: 17 },
      { id: 'P5', name: 'Port 05 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P6', name: 'Port 06 (Bharat DC)', type: 'GB/T & DC001', powerKw: 30, status: 'charging', pricePerKwh: 14 },
      { id: 'P7', name: 'Port 07 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
      { id: 'P8', name: 'Port 08 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 13 },
    ],
    description: 'Premier Tata Power EZ Charge MegaHub at Balewadi High Street Baner. Equipped with 120kW fast dual-gun DC chargers, surrounding cafés, and valet parking.',
  },
  {
    id: 'PUNE_MG_VIMAN',
    city: 'pune',
    cityName: 'Pune, Maharashtra',
    company: 'MG',
    brandColor: '#00539B',
    stationName: 'MG SuperCharge Hub - Phoenix Marketcity',
    address: 'Phoenix Marketcity Mall, Viman Nagar, Pune, Maharashtra - 411014',
    shortAddress: 'Viman Nagar, Pune',
    latitude: 18.5620,
    longitude: 73.9168,
    distanceKm: 4.2,
    time: '12-14 Mins',
    timeMinutes: 12,
    image: morrisChargerImage,
    rating: 4.8,
    reviewsCount: 395,
    openHours: 'Open 24/7',
    totalPorts: 6,
    availablePortsCount: 4,
    maxPowerKw: 60,
    pricePerKwh: 17,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['Shopping Mall', 'Cinema', 'Food Court', 'Covered Parking', 'ATM'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'charging', pricePerKwh: 17 },
      { id: 'P4', name: 'Port 04 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P5', name: 'Port 05 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
      { id: 'P6', name: 'Port 06 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 13 },
    ],
    description: 'Ultra-convenient destination charging at Phoenix Marketcity Viman Nagar. Shop, dine, and catch a movie while your vehicle charges with 60kW DC power.',
  },
  {
    id: 'PUNE_MAHINDRA_KP',
    city: 'pune',
    cityName: 'Pune, Maharashtra',
    company: 'Mahindra',
    brandColor: '#C8102E',
    stationName: 'Mahindra Born Electric Hub - Koregaon Park',
    address: 'North Main Road, Koregaon Park, Pune, Maharashtra - 411001',
    shortAddress: 'Koregaon Park, Pune',
    latitude: 18.5362,
    longitude: 73.8940,
    distanceKm: 3.5,
    time: '10-12 Mins',
    timeMinutes: 10,
    image: mahindraChargerStation,
    rating: 4.7,
    reviewsCount: 312,
    openHours: 'Open 24/7',
    totalPorts: 6,
    availablePortsCount: 5,
    maxPowerKw: 90,
    pricePerKwh: 17,
    connectorTypes: ['CCS-2', 'Bharat DC-001', 'Type-2 AC'],
    amenities: ['Customer Lounge', 'Organic Café', 'Restrooms', 'High-Speed Wi-Fi'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 90, status: 'available', pricePerKwh: 17 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 90, status: 'available', pricePerKwh: 17 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 16 },
      { id: 'P4', name: 'Port 04 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'charging', pricePerKwh: 16 },
      { id: 'P5', name: 'Port 05 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
      { id: 'P6', name: 'Port 06 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
    ],
    description: 'State-of-the-art Mahindra fast charging hub in the heart of Koregaon Park with green solar-assisted canopy and artisan cafés next door.',
  },
  {
    id: 'PUNE_TATA_WAKAD',
    city: 'pune',
    cityName: 'Pune, Maharashtra',
    company: 'Tata',
    brandColor: '#0072CE',
    stationName: 'Tata Power EV Hub - Wakad Flyover',
    address: 'Datta Mandir Road, Near Wakad Bridge, Pune - 411057',
    shortAddress: 'Wakad Bridge, Pune',
    latitude: 18.5987,
    longitude: 73.7628,
    distanceKm: 2.8,
    time: '7-9 Mins',
    timeMinutes: 8,
    image: tataChargerImage,
    rating: 4.6,
    reviewsCount: 270,
    openHours: 'Open 24/7',
    totalPorts: 4,
    availablePortsCount: 3,
    maxPowerKw: 60,
    pricePerKwh: 17,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['Snack Bar', 'Air Pressure Point', 'Restrooms', '24/7 Security'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P4', name: 'Port 04 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 13 },
    ],
    description: 'Quick top-up point located right at Wakad Highway junction. Ideal for drivers heading toward Hinjawadi or Pune bypass.',
  },
  {
    id: 'PUNE_MAHINDRA_KHARADI',
    city: 'pune',
    cityName: 'Pune, Maharashtra',
    company: 'Mahindra',
    brandColor: '#C8102E',
    stationName: 'Mahindra ChargePoint Express - Kharadi EON',
    address: 'EON Free Zone Phase 1, Kharadi, Pune, Maharashtra - 411014',
    shortAddress: 'EON Free Zone, Kharadi, Pune',
    latitude: 18.5516,
    longitude: 73.9515,
    distanceKm: 5.4,
    time: '14-16 Mins',
    timeMinutes: 15,
    image: mahindraChargerStation,
    rating: 4.6,
    reviewsCount: 195,
    openHours: 'Open 24/7',
    totalPorts: 4,
    availablePortsCount: 3,
    maxPowerKw: 60,
    pricePerKwh: 17,
    connectorTypes: ['CCS-2', 'Bharat DC-001', 'Type-2 AC'],
    amenities: ['Tech Park Cafeteria', 'Restrooms', '24/7 Security', 'Free Wi-Fi'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P4', name: 'Port 04 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 13 },
    ],
    description: 'Fast charging station inside EON IT Park Kharadi with rapid DC units and seamless automated app activation.',
  },
  {
    id: 'PUNE_EXPRESSWAY_URSE',
    city: 'pune',
    cityName: 'Pune, Maharashtra',
    company: 'Tata',
    brandColor: '#0072CE',
    stationName: 'Tata Power MegaHub - Pune-Mumbai Expressway',
    address: 'Urse Toll Plaza Food Mall, Pune-Mumbai Expressway - 410506',
    shortAddress: 'Urse Plaza, Expressway',
    latitude: 18.7302,
    longitude: 73.6521,
    distanceKm: 18.4,
    time: '22-26 Mins',
    timeMinutes: 24,
    image: tataChargerImage,
    rating: 4.9,
    reviewsCount: 1140,
    openHours: 'Open 24/7',
    totalPorts: 8,
    availablePortsCount: 6,
    maxPowerKw: 150,
    pricePerKwh: 19,
    connectorTypes: ['CCS-2', 'Type-2 AC', 'GB/T'],
    amenities: ['Highway Food Court', 'McDonalds & Starbucks', 'Clean Restrooms', 'EV Lounge', 'Tire Care'],
    ports: [
      { id: 'P1', name: 'Port 01 (150kW Ultra Fast)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 19 },
      { id: 'P2', name: 'Port 02 (150kW Ultra Fast)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 19 },
      { id: 'P3', name: 'Port 03 (60kW Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P4', name: 'Port 04 (60kW Fast DC)', type: 'CCS-2', powerKw: 60, status: 'charging', pricePerKwh: 17 },
      { id: 'P5', name: 'Port 05 (60kW Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P6', name: 'Port 06 (60kW Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P7', name: 'Port 07 (22kW AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 14 },
      { id: 'P8', name: 'Port 08 (22kW AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 14 },
    ],
    description: 'Flagship Highway MegaHub on the Pune-Mumbai Expressway at Urse. Massive 150kW ultra-fast bays with complete dining, restroom, and convenience plaza.',
  },
  {
    id: 'PUNE_TESLA_SBROAD',
    city: 'pune',
    cityName: 'Pune, Maharashtra',
    company: 'Tesla',
    brandColor: '#E82127',
    stationName: 'Tesla Destination Point - The Pavillion, SB Road',
    address: 'The Pavillion Mall, Senapati Bapat Road, Pune, Maharashtra - 411016',
    shortAddress: 'SB Road, Pune',
    latitude: 18.5314,
    longitude: 73.8296,
    distanceKm: 2.9,
    time: '8-10 Mins',
    timeMinutes: 8,
    image: teslaChargerImage,
    rating: 4.8,
    reviewsCount: 310,
    openHours: '10:00 AM - 11:30 PM',
    totalPorts: 4,
    availablePortsCount: 3,
    maxPowerKw: 150,
    pricePerKwh: 22,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['Luxury Shopping', 'PVR Cinema', 'Food Court', 'Underground Parking'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'charging', pricePerKwh: 22 },
      { id: 'P4', name: 'Port 04 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 15 },
    ],
    description: 'High-end destination charging inside The Pavillion Mall at Senapati Bapat Road.',
  },

  // ==========================================
  // DELHI NCR & GURUGRAM HUBS
  // ==========================================
  {
    id: 'TS1',
    city: 'delhi',
    cityName: 'Delhi NCR & Gurugram',
    company: 'Tesla',
    brandColor: '#E82127',
    stationName: 'Tesla Supercharger Hub 103 - Cyber City',
    address: 'DLF Cyber City, Building 10, Gurugram, Haryana - 122002',
    shortAddress: 'DLF Cyber City, Gurugram',
    latitude: 28.4952,
    longitude: 77.0892,
    distanceKm: 2.4,
    time: '8-10 Mins',
    timeMinutes: 8,
    image: teslaChargerImage,
    rating: 4.9,
    reviewsCount: 342,
    openHours: 'Open 24/7',
    totalPorts: 8,
    availablePortsCount: 6,
    maxPowerKw: 250,
    pricePerKwh: 24,
    connectorTypes: ['Tesla Supercharger', 'CCS-2'],
    amenities: ['Café & Lounge', 'Restrooms', 'High-Speed Wi-Fi', '24/7 Security'],
    ports: [
      { id: 'P1', name: 'Port 01 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 24 },
      { id: 'P2', name: 'Port 02 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 24 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P4', name: 'Port 04 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 16 },
    ],
    description: 'Ultra-fast Tesla V3 Supercharging Hub at DLF Cyber City.',
  },
  {
    id: 'T1',
    city: 'delhi',
    cityName: 'Delhi NCR & Gurugram',
    company: 'Tata',
    brandColor: '#0072CE',
    stationName: 'Tata Power EZ Charge MegaHub A-4 - NH 48',
    address: 'NH 48 Expressway, Sector 34, Gurugram - 122004',
    shortAddress: 'NH 48 Expressway, Gurugram',
    latitude: 28.4350,
    longitude: 77.0142,
    distanceKm: 3.8,
    time: '12-15 Mins',
    timeMinutes: 12,
    image: tataChargerImage,
    rating: 4.8,
    reviewsCount: 512,
    openHours: 'Open 24/7',
    totalPorts: 8,
    availablePortsCount: 5,
    maxPowerKw: 120,
    pricePerKwh: 18,
    connectorTypes: ['CCS-2', 'Bharat DC-001', 'Type-2 AC'],
    amenities: ['24/7 Food Plaza', 'Clean Washrooms', 'Tire Pressure Check', 'Free Wi-Fi'],
    ports: [
      { id: 'P1', name: 'Port 01 (Dual Gun DC)', type: 'CCS-2', powerKw: 120, status: 'available', pricePerKwh: 18 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
    ],
    description: 'Flagship Tata Power EZ Charge MegaHub on Delhi-Jaipur NH48.',
  },

  // ==========================================
  // MUMBAI HUBS
  // ==========================================
  {
    id: 'MUMBAI_TESLA_BKC',
    city: 'mumbai',
    cityName: 'Mumbai, Maharashtra',
    company: 'Tesla',
    brandColor: '#E82127',
    stationName: 'Tesla Supercharger Hub - BKC Mumbai',
    address: 'Maker Maxity, Bandra Kurla Complex, Mumbai - 400051',
    shortAddress: 'BKC, Mumbai',
    latitude: 19.0664,
    longitude: 72.8687,
    distanceKm: 3.1,
    time: '8-10 Mins',
    timeMinutes: 8,
    image: teslaChargerImage,
    rating: 4.9,
    reviewsCount: 530,
    openHours: 'Open 24/7',
    totalPorts: 6,
    availablePortsCount: 4,
    maxPowerKw: 250,
    pricePerKwh: 24,
    connectorTypes: ['Tesla Supercharger', 'CCS-2'],
    amenities: ['Fine Dining', 'Valet Parking', 'EV Lounge', 'Security'],
    ports: [
      { id: 'P1', name: 'Port 01 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 24 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
    ],
    description: 'Premier Tesla V3 Supercharger at Bandra Kurla Complex, Mumbai.',
  },
];

export default stations;