import teslaChargerImage from '../assets/charginStationTesla.jpeg';
import mahindraChargerStation from '../assets/chargingStationMahindra.jpeg';
import tataChargerImage from '../assets/chargingStationTata.jpeg';
import morrisChargerImage from '../assets/chargingStationMorris.jpeg';

export const currentUser = {
  name: 'Alex Rivera',
  email: 'alex.rivera@evdriver.com',
  vehicle: {
    model: 'Tata Nexon EV Max',
    brand: 'Tata',
    batteryCapacityKwh: 40.5,
    currentBatteryPct: 78,
    estimatedRangeKm: 284,
    maxRangeKm: 437,
    portType: 'CCS-2',
    fastChargeSpeedKw: 50,
  },
  defaultLocation: {
    latitude: 28.4980,
    longitude: 77.0850,
    address: 'Cyber Hub, DLF Phase 2, Gurugram',
    city: 'Gurugram & Delhi NCR',
  },
  walletBalance: 1450,
  currency: '₹',
  totalKwhCharged: 218.4,
  co2SavedKg: 136.8,
  savedStations: ['TS1', 'T1'],
};

export const manufacturerBrands = [
  { id: 'all', name: 'All Stations', icon: 'flash', color: '#05B66B' },
  { id: 'Tesla', name: 'Tesla', icon: 'car-sport', color: '#E82127' },
  { id: 'Tata', name: 'Tata Power', icon: 'battery-charging', color: '#0072CE' },
  { id: 'Mahindra', name: 'Mahindra', icon: 'shield-checkmark', color: '#C8102E' },
  { id: 'MG', name: 'Morris Garages', icon: 'speedometer', color: '#00539B' },
];

export const stations = [
  // Tesla Stations
  {
    id: 'TS1',
    company: 'Tesla',
    brandColor: '#E82127',
    stationName: 'Tesla Supercharger Hub 103',
    address: 'DLF Cyber City, Building 10, Gurugram, Haryana - 122002',
    shortAddress: 'DLF Cyber City, Gurugram',
    latitude: 28.4952,
    longitude: 77.0892,
    distanceKm: 2.4,
    time: '8-10 Mins',
    timeMinutes: 8,
    image: teslaChargerImage,
    rating: 4.9,
    reviewsCount: 342,
    openHours: 'Open 24/7',
    totalPorts: 8,
    availablePortsCount: 6,
    maxPowerKw: 250,
    pricePerKwh: 24,
    connectorTypes: ['Tesla Supercharger', 'CCS-2'],
    amenities: ['Café & Lounge', 'Restrooms', 'High-Speed Wi-Fi', '24/7 Security', 'Valet Parking'],
    ports: [
      { id: 'P1', name: 'Port 01 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 24 },
      { id: 'P2', name: 'Port 02 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 24 },
      { id: 'P3', name: 'Port 03 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'charging', pricePerKwh: 24 },
      { id: 'P4', name: 'Port 04 (V3 Supercharger)', type: 'CCS-2 / NACS', powerKw: 250, status: 'available', pricePerKwh: 24 },
      { id: 'P5', name: 'Port 05 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P6', name: 'Port 06 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P7', name: 'Port 07 (AC Type 2)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 16 },
      { id: 'P8', name: 'Port 08 (AC Type 2)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 16 },
    ],
    description: 'Ultra-fast Tesla V3 Supercharging Hub located at prime DLF Cyber City with premium lounge, high-speed amenities, and 24/7 security.',
  },
  {
    id: 'TS2',
    company: 'Tesla',
    brandColor: '#E82127',
    stationName: 'Tesla Destination Point 102',
    address: 'Aerocity Worldmark 3, New Delhi - 110037',
    shortAddress: 'Aerocity, New Delhi',
    latitude: 28.5502,
    longitude: 77.1210,
    distanceKm: 5.1,
    time: '15-18 Mins',
    timeMinutes: 15,
    image: teslaChargerImage,
    rating: 4.8,
    reviewsCount: 198,
    openHours: 'Open 24/7',
    totalPorts: 6,
    availablePortsCount: 4,
    maxPowerKw: 150,
    pricePerKwh: 22,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['Restaurants', 'Airport Shuttle', 'Restrooms', 'Free Wi-Fi'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'charging', pricePerKwh: 22 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P4', name: 'Port 04 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P5', name: 'Port 05 (AC Type 2)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 15 },
      { id: 'P6', name: 'Port 06 (AC Type 2)', type: 'Type-2 AC', powerKw: 22, status: 'maintenance', pricePerKwh: 15 },
    ],
    description: 'Convenient charging hub in Aerocity hotel district with direct airport highway access and dining facilities.',
  },
  {
    id: 'TS3',
    company: 'Tesla',
    brandColor: '#E82127',
    stationName: 'Tesla Supercharger Hub 101',
    address: 'Select CITYWALK Mall, Saket, New Delhi - 110017',
    shortAddress: 'Saket, New Delhi',
    latitude: 28.5284,
    longitude: 77.2185,
    distanceKm: 8.7,
    time: '20-25 Mins',
    timeMinutes: 22,
    image: teslaChargerImage,
    rating: 4.7,
    reviewsCount: 287,
    openHours: '10:00 AM - 11:30 PM',
    totalPorts: 6,
    availablePortsCount: 3,
    maxPowerKw: 150,
    pricePerKwh: 22,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['Shopping Mall', 'Cinema', 'Food Court', 'Wheelchair Accessible'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'available', pricePerKwh: 22 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'charging', pricePerKwh: 22 },
      { id: 'P4', name: 'Port 04 (Fast DC)', type: 'CCS-2', powerKw: 150, status: 'charging', pricePerKwh: 22 },
      { id: 'P5', name: 'Port 05 (AC Type 2)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 15 },
      { id: 'P6', name: 'Port 06 (AC Type 2)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 15 },
    ],
    description: 'Basement Level 2 charging bays inside Select CITYWALK Saket. Shop and dine while your EV charges.',
  },

  // Tata Power Stations
  {
    id: 'T1',
    company: 'Tata',
    brandColor: '#0072CE',
    stationName: 'Tata Power EZ Charge MegaHub A-4',
    address: 'NH 48 Expressway, Sector 34, Gurugram - 122004',
    shortAddress: 'NH 48 Expressway, Gurugram',
    latitude: 28.4350,
    longitude: 77.0142,
    distanceKm: 3.8,
    time: '12-15 Mins',
    timeMinutes: 12,
    image: tataChargerImage,
    rating: 4.8,
    reviewsCount: 512,
    openHours: 'Open 24/7',
    totalPorts: 8,
    availablePortsCount: 5,
    maxPowerKw: 120,
    pricePerKwh: 18,
    connectorTypes: ['CCS-2', 'Bharat DC-001', 'Type-2 AC'],
    amenities: ['24/7 Food Plaza', 'Clean Washrooms', 'Tire Pressure Check', 'Free Wi-Fi', 'EV Lounge'],
    ports: [
      { id: 'P1', name: 'Port 01 (Dual Gun DC)', type: 'CCS-2', powerKw: 120, status: 'available', pricePerKwh: 18 },
      { id: 'P2', name: 'Port 02 (Dual Gun DC)', type: 'CCS-2', powerKw: 120, status: 'available', pricePerKwh: 18 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P4', name: 'Port 04 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'charging', pricePerKwh: 17 },
      { id: 'P5', name: 'Port 05 (Bharat DC)', type: 'GB/T & DC001', powerKw: 30, status: 'available', pricePerKwh: 14 },
      { id: 'P6', name: 'Port 06 (Bharat DC)', type: 'GB/T & DC001', powerKw: 30, status: 'charging', pricePerKwh: 14 },
      { id: 'P7', name: 'Port 07 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
      { id: 'P8', name: 'Port 08 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 13 },
    ],
    description: 'Flagship Tata Power EZ Charge MegaHub on Delhi-Jaipur NH48. Features 120kW ultra-fast dual-gun DC chargers and full highway rest facilities.',
  },
  {
    id: 'T2',
    company: 'Tata',
    brandColor: '#0072CE',
    stationName: 'Tata Power Fast Point B-3',
    address: 'Ambience Mall, NH 8, Gurugram, Haryana - 122002',
    shortAddress: 'Ambience Mall, Gurugram',
    latitude: 28.5048,
    longitude: 77.0970,
    distanceKm: 4.6,
    time: '14-16 Mins',
    timeMinutes: 14,
    image: tataChargerImage,
    rating: 4.6,
    reviewsCount: 310,
    openHours: 'Open 24/7',
    totalPorts: 4,
    availablePortsCount: 3,
    maxPowerKw: 60,
    pricePerKwh: 18,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['Shopping', 'Cinema', 'Café', 'Covered Parking'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 18 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 18 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 18 },
      { id: 'P4', name: 'Port 04 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 14 },
    ],
    description: 'High-speed charging bays inside Ambience Mall multilevel parking with direct mall entrance.',
  },

  // Mahindra Stations
  {
    id: 'MH1',
    company: 'Mahindra',
    brandColor: '#C8102E',
    stationName: 'Mahindra ChargePoint Hub 543',
    address: 'Mahindra Towers, Road No 13, Okhla Phase 3, New Delhi - 110020',
    shortAddress: 'Okhla Phase 3, New Delhi',
    latitude: 28.5363,
    longitude: 77.2721,
    distanceKm: 6.2,
    time: '18-22 Mins',
    timeMinutes: 18,
    image: mahindraChargerStation,
    rating: 4.7,
    reviewsCount: 220,
    openHours: 'Open 24/7',
    totalPorts: 6,
    availablePortsCount: 4,
    maxPowerKw: 90,
    pricePerKwh: 17,
    connectorTypes: ['CCS-2', 'Bharat DC-001', 'Type-2 AC'],
    amenities: ['Customer Lounge', 'EV Service Center', 'Restrooms', 'Free Wi-Fi'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 90, status: 'available', pricePerKwh: 17 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 90, status: 'available', pricePerKwh: 17 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'charging', pricePerKwh: 16 },
      { id: 'P4', name: 'Port 04 (Bharat DC)', type: 'GB/T & DC001', powerKw: 30, status: 'available', pricePerKwh: 14 },
      { id: 'P5', name: 'Port 05 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
      { id: 'P6', name: 'Port 06 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 13 },
    ],
    description: 'Mahindra Born Electric certified fast charging hub with dedicated customer support and high-speed DC units.',
  },
  {
    id: 'MH2',
    company: 'Mahindra',
    brandColor: '#C8102E',
    stationName: 'Mahindra ChargePoint Express 541',
    address: 'Golf Course Extension Road, Sector 65, Gurugram - 122102',
    shortAddress: 'Sector 65, Gurugram',
    latitude: 28.3985,
    longitude: 77.0702,
    distanceKm: 7.5,
    time: '20-25 Mins',
    timeMinutes: 22,
    image: mahindraChargerStation,
    rating: 4.5,
    reviewsCount: 164,
    openHours: 'Open 24/7',
    totalPorts: 4,
    availablePortsCount: 2,
    maxPowerKw: 60,
    pricePerKwh: 17,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['Convenience Store', 'ATM', 'Restrooms', 'Security'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'charging', pricePerKwh: 17 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 17 },
      { id: 'P4', name: 'Port 04 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'charging', pricePerKwh: 13 },
    ],
    description: 'Convenient charging location along Golf Course Extension with seamless 24/7 automated access.',
  },

  // Morris Garages (MG) Stations
  {
    id: 'MG1',
    company: 'MG',
    brandColor: '#00539B',
    stationName: 'MG SuperCharge Hub 4',
    address: 'MG Motor Flagship, Plot 43, Sector 32, Gurugram - 122001',
    shortAddress: 'Sector 32, Gurugram',
    latitude: 28.4552,
    longitude: 77.0468,
    distanceKm: 3.2,
    time: '10-12 Mins',
    timeMinutes: 10,
    image: morrisChargerImage,
    rating: 4.8,
    reviewsCount: 284,
    openHours: 'Open 24/7',
    totalPorts: 6,
    availablePortsCount: 5,
    maxPowerKw: 60,
    pricePerKwh: 16,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['MG Customer Lounge', 'Coffee Bar', 'High-Speed Wi-Fi', '24/7 Security', 'EV Diagnostic Station'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 16 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 16 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'available', pricePerKwh: 16 },
      { id: 'P4', name: 'Port 04 (Fast DC)', type: 'CCS-2', powerKw: 60, status: 'charging', pricePerKwh: 16 },
      { id: 'P5', name: 'Port 05 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
      { id: 'P6', name: 'Port 06 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
    ],
    description: 'MG Supercharge station equipped with 60kW DC Fast chargers compatible with all CCS2 electric vehicles. Premium hospitality lounge available.',
  },
  {
    id: 'MG2',
    company: 'MG',
    brandColor: '#00539B',
    stationName: 'MG Chargers Point 13',
    address: 'Worldmark Sector 65, Maidawas Rd, Gurugram - 122018',
    shortAddress: 'Worldmark 65, Gurugram',
    latitude: 28.4010,
    longitude: 77.0650,
    distanceKm: 6.8,
    time: '18-22 Mins',
    timeMinutes: 19,
    image: morrisChargerImage,
    rating: 4.6,
    reviewsCount: 156,
    openHours: 'Open 24/7',
    totalPorts: 4,
    availablePortsCount: 3,
    maxPowerKw: 50,
    pricePerKwh: 17,
    connectorTypes: ['CCS-2', 'Type-2 AC'],
    amenities: ['Fine Dining', 'Supermarket', 'Restrooms', 'Underground Parking'],
    ports: [
      { id: 'P1', name: 'Port 01 (Fast DC)', type: 'CCS-2', powerKw: 50, status: 'available', pricePerKwh: 17 },
      { id: 'P2', name: 'Port 02 (Fast DC)', type: 'CCS-2', powerKw: 50, status: 'available', pricePerKwh: 17 },
      { id: 'P3', name: 'Port 03 (Fast DC)', type: 'CCS-2', powerKw: 50, status: 'charging', pricePerKwh: 17 },
      { id: 'P4', name: 'Port 04 (Fast AC)', type: 'Type-2 AC', powerKw: 22, status: 'available', pricePerKwh: 13 },
    ],
    description: 'Premium destination charging at Worldmark 65. Enjoy dining and shopping while your EV fast charges.',
  },
];

export default stations;